35294 edit celonis documentation
ploetz-zeller/symbio-documentation pull request #176
Opened 2020-11-26 16:09 UTC by saschabartsch

**Created Documentation Entry for the Celonis Process Mining Connector**

This pull request contains an additional entry for the Celonis Process Mining connector. It covers the processes of configuration as well as the usage of the service.

2020-11-26 22:21 UTC, thomashauser requested changes

2020-11-26 22:21 UTC, thomashauser commented on mkdocs.yml
> +        - Process Export: admin/services/celonis-process-mining-connector/usage_push.md
`Push to Celonis` instead of `Process Export`

2020-11-26 22:21 UTC, thomashauser commented on mkdocs.yml
> +        - Process Import: admin/services/celonis-process-mining-connector/usage_pull.md
`Pull from Celonis` instead of `Process Import`

2020-11-27 10:51 UTC, saschabartsch commented on docs/admin/services/celonis-process-mining-connector/configuration.md
> +   1. **Name:** (Preferred Name, e.g. Celonis Process Mining Connector)
Are you sure? Because at this line in the documentation, we are setting the External System Type and not the Name of the External System itself. The Name of the External System is set later on and I would guess that this is the right spot to give it the Celonis Team name

2020-11-29 19:06 UTC, thomashauser commented on docs/admin/services/celonis-process-mining-connector/configuration.md
> +   1. **Name:** (Preferred Name, e.g. Celonis Process Mining Connector)
Oh, yes, you are right.

2020-11-29 19:17 UTC, thomashauser approved these changes

2020-11-29 19:17 UTC, merged