Origin/37414 check and enhance documentation
ploetz-zeller/symbio-documentation pull request #194
Opened 2021-02-22 16:43 UTC by KabbaniReem

changes are made here for the new feature "Permissions directly on process/object"

2021-02-26 10:38 UTC, JochenLinnemann requested changes
At least the images marked need adjustment.

2021-02-26 10:38 UTC, JochenLinnemann commented on docs/admin/administration/permissions/permission-levels-explained.md
>  ## General Permissions
I liked the logical ordering by "increasing" rights way better than the ordering by now arbitrary enum constant values.

2021-02-26 10:38 UTC, JochenLinnemann commented on docs/admin/administration/permissions/permission-levels-explained.md
>    ![](media/activating-feature-architectural-permissions-2.png)
This images must be changed, it still shows the old feature title.

2021-02-26 10:38 UTC, JochenLinnemann commented on docs/admin/administration/permissions/permissions-maintenance-extension.md
> +![screen](./media/no_permissionsset.png)
This image is not showing in the preview.

2021-02-26 10:38 UTC, JochenLinnemann commented on docs/admin/administration/permissions/permissions-maintenance-extension.md
> +- __permission set without any permissions__: In this case you may select a permission set without any mermissions, see image below; which means the permissions on the selected process/object are exc
Does this hold true even when permission inheritance is set to inherit from the parent or default?

2021-02-26 10:38 UTC, JochenLinnemann commented on docs/admin/administration/permissions/permissions-maintenance-extension.md
> +- __no permission sets at all__: Already granted permissions of other users remain unaffected.
Does this hold true even when you select "start without any permission" in the inheritance dropdown?

2021-02-26 13:07 UTC, KabbaniReem commented on docs/admin/administration/permissions/permission-levels-explained.md
>  ## General Permissions
I relisted them exactly as displayed in symbio, so that a reader does not get lost, that's all!

2021-02-26 13:29 UTC, KabbaniReem reviewed
kindly check my question

2021-02-26 13:29 UTC, KabbaniReem commented on docs/admin/administration/permissions/permissions-maintenance-extension.md
> +![screen](./media/no_permissionsset.png)
it's an image added to the directory of images, it's truely shown in VS Code but practically did not notice it's new, any ideas?

2021-02-26 13:47 UTC, JochenLinnemann commented on docs/admin/administration/permissions/permissions-maintenance-extension.md
> +![screen](./media/no_permissionsset.png)
no idea, but when it is visible in the final build then everything is OK

2021-02-26 13:48 UTC, JochenLinnemann commented on docs/admin/administration/permissions/permission-levels-explained.md
>    ![](media/activating-feature-architectural-permissions-2.png)
This image still does not match the new title

2021-02-26 13:48 UTC, JochenLinnemann requested changes
Still one image to go: Activating the feature shows the old title of the feature.

2021-03-02 13:20 UTC, JochenLinnemann approved these changes

2021-03-02 13:35 UTC, Gerrit-P-und-Z approved these changes

2021-03-02 13:35 UTC, merged