Pbi/38285 add faq to reporting installation documentation
ploetz-zeller/symbio-documentation pull request #199
Opened 2021-03-15 09:57 UTC by KabbaniReem

Here are updates concerning installation of reporting locally by adding more info and updating FAQ with some problems and corresponding solutions for.

2021-03-16 12:00 UTC, JochenLinnemann reviewed
I don't like mixing topics in a pull request. Here we have permission and reporting in one PR...

2021-03-16 13:25 UTC, KabbaniReem commented
> I don't like mixing topics in a pull request. Here we have permission and reporting in one PR...
This was not ment to be this way, I thought I have made the PR to be merged with master. Sorry for that!

2021-03-16 13:53 UTC, KabbaniReem commented
I reverted the changes in commits about reporting since they are already in master, should this cause any problems? @JochenLinnemann

2021-03-16 14:40 UTC, Gerrit-P-und-Z submitted a review, later dismissed

2021-03-17 07:08 UTC, JochenLinnemann requested changes

2021-03-17 07:08 UTC, JochenLinnemann commented on docs/admin/services/reporting-service/faq.md
> +  - Can the account that is running under Symbio Core do the same?
Can the account that is running Symbio Core do the same?

2021-03-17 07:08 UTC, JochenLinnemann commented on docs/admin/services/reporting-service/faq.md
> +  - Can the account that is running under Symbio Core do the same?
strike "under"

2021-03-17 07:08 UTC, JochenLinnemann commented on docs/admin/services/reporting-service/faq.md
> +  - Can the account that is running under the Reporting Connector do the same?
strike "under"

2021-03-17 07:08 UTC, JochenLinnemann commented on docs/admin/services/reporting-service/faq.md
> +  - Can the account that is running under the Reporting Connector do the same?
strike "under"

2021-03-17 07:08 UTC, JochenLinnemann commented on docs/admin/services/reporting-service/faq.md
> +  - Can the account that is running under the Reporting Connector do the same?
strike "under"

2021-03-17 07:08 UTC, JochenLinnemann commented on docs/admin/services/reporting-service/faq.md
> +  - Can the account that is running under scheduled tasks do the same?
strike "under"

2021-03-17 07:08 UTC, JochenLinnemann commented on docs/admin/services/reporting-service/faq.md
> +  - Can the account that is running under scheduled tasks do the same?
strike "under"

2021-03-17 07:08 UTC, JochenLinnemann commented on docs/admin/services/reporting-service/faq.md
> +  - Can the account that is running under scheduled tasks do the same?
strike "under"

2021-03-17 07:08 UTC, JochenLinnemann commented on docs/admin/services/reporting-service/reporting-connector.md
> +2. After building the reporting project, which contains Conector Service, Copy all the debug/release files and folders of the service into this directory.
The customer will NOT build. This documentation is customer-facing...

2021-03-17 07:08 UTC, JochenLinnemann commented on docs/admin/services/reporting-service/reporting-connector.md
> +    1. Create a new Application pool (No Managed Code/Integrated) and assign a user account with appropriate rights (full Control) to the created directory in step 1.
"Full Control" or "full control"

2021-03-17 07:08 UTC, JochenLinnemann commented on docs/admin/services/reporting-service/reporting-connector.md
> +4. Configure the Connector by editing its appsettings.config files (can be found among the resulting build files).
The customer has no "build" files

2021-03-17 07:08 UTC, JochenLinnemann commented on docs/admin/services/reporting-service/ssrs-and-reports.md
> +You may keep on all default settings here if you want.
You may keep on all default settings here if you want. - "keep on" = activate?

2021-03-17 07:08 UTC, JochenLinnemann commented on docs/admin/services/reporting-service/reporting-console.md
> +2. After building the reporting project, which contains the Console Service, Copy all the debug/release files and folders of the service into this directory.
The customer will NOT build the project!

2021-03-17 07:09 UTC, JochenLinnemann commented
> I reverted the changes in commits about reporting since they are already in master, should this cause any problems? @JochenLinnemann

I would have expected problems but the system is not showing any deletions so it seems to be OK.

2021-03-17 07:11 UTC, JochenLinnemann commented
Please remember the audience of this documentation. It is not "developers at Symbioworld" but customers with no access to the source code. Please move internal FAQ content to our developer Wiki, especially things using the terms "build", "release", "debug".

2021-03-17 08:42 UTC, KabbaniReem commented on docs/admin/services/reporting-service/faq.md
> +  - Can the account that is running under Symbio Core do the same?
Apparently I could not understand the meaning of the original sentence "Can the account Symbio Core is running under do the same"; I mean grammatically it has a problem causing the sentence not being understood, can you please reformulate it for me and I shall change it accordingly in other positions?

2021-03-17 08:44 UTC, KabbaniReem commented on docs/admin/services/reporting-service/reporting-connector.md
> +2. After building the reporting project, which contains Conector Service, Copy all the debug/release files and folders of the service into this directory.
where from should the customer copy the files then?

2021-03-17 08:44 UTC, KabbaniReem commented on docs/admin/services/reporting-service/reporting-connector.md
> +    1. Create a new Application pool (No Managed Code/Integrated) and assign a user account with appropriate rights (full Control) to the created directory in step 1.
I shall change it

2021-03-17 08:45 UTC, KabbaniReem commented on docs/admin/services/reporting-service/reporting-connector.md
> +4. Configure the Connector by editing its appsettings.config files (can be found among the resulting build files).
where from should the customer copy the files then?

2021-03-17 08:46 UTC, KabbaniReem commented on docs/admin/services/reporting-service/ssrs-and-reports.md
> +You may keep on all default settings here if you want.
I just meant he does not need to change other default settings at this step

2021-03-17 09:11 UTC, KabbaniReem commented on docs/admin/services/reporting-service/faq.md
> +  - Can the account that is running under Symbio Core do the same?
I striked the word "under"

2021-03-17 09:11 UTC, KabbaniReem commented on docs/admin/services/reporting-service/faq.md
> +  - Can the account that is running under Symbio Core do the same?
done

2021-03-17 09:11 UTC, KabbaniReem commented on docs/admin/services/reporting-service/faq.md
> +  - Can the account that is running under the Reporting Connector do the same?
done

2021-03-17 09:11 UTC, KabbaniReem commented on docs/admin/services/reporting-service/faq.md
> +  - Can the account that is running under the Reporting Connector do the same?
done

2021-03-17 09:12 UTC, KabbaniReem commented on docs/admin/services/reporting-service/faq.md
> +  - Can the account that is running under the Reporting Connector do the same?
done

2021-03-17 09:14 UTC, KabbaniReem commented on docs/admin/services/reporting-service/reporting-console.md
> +2. After building the reporting project, which contains the Console Service, Copy all the debug/release files and folders of the service into this directory.
you are right, I deleted all mentions of build/release in this documentation.

2021-03-17 10:28 UTC, JochenLinnemann submitted a review, later dismissed

2021-03-17 10:28 UTC, JochenLinnemann commented on docs/admin/services/reporting-service/reporting-connector.md
> +4. Configure the Connector by editing its appsettings.config files (can be found among the resulting build files).
FTP

2021-03-17 10:30 UTC, JochenLinnemann commented on docs/admin/services/reporting-service/ssrs-and-reports.md
> +You may keep on all default settings here if you want.
keep on = mach weiter
keep to = bleib bei

2021-03-17 10:30 UTC, JochenLinnemann commented on docs/admin/services/reporting-service/reporting-connector.md
> +2. After building the reporting project, which contains Conector Service, Copy all the debug/release files and folders of the service into this directory.
FTP

2021-03-17 12:55 UTC, JochenLinnemann approved these changes

2021-03-17 12:55 UTC, merged