Added documentation for facet view table
ploetz-zeller/symbio-documentation pull request #200
Opened 2021-03-17 14:26 UTC by saschabartsch

**custom-view-for-table-widget.md**
- Actual documentation file
**Media-Folder**
- Added necessary screenshots
**mkdocs.yml**
- Added navigation entry

**Description**
Added a documentation for the new feature **Custom views for table widget**

2021-03-18 11:57 UTC, thomashauser requested changes
Separate documentation for consolidation of 'create dropdown value' customizations is missing. Do we create a separate PR for that?

2021-03-18 11:57 UTC, thomashauser commented on mkdocs.yml
> +        - "Fact Sheets: Custom views for table widget": admin/features/process-design/custom-views-for-table-widget/custom-views-for-table-widget.md
Move it to general design

2021-03-18 13:05 UTC, saschabartsch commented
> 
> 
> Separate documentation for consolidation of 'create dropdown value' customizations is missing. Do we create a separate PR for that?

I don't think we need a seperate PR for that since it was part of the same PBI. I am just not familiar with these changes. You can show me what changed and I will create another entry in the documentation

2021-03-18 16:29 UTC, saschabartsch commented on mkdocs.yml
> +        - "Fact Sheets: Custom views for table widget": admin/features/process-design/custom-views-for-table-widget/custom-views-for-table-widget.md
done

2021-03-19 15:42 UTC, saschabartsch commented on docs/admin/features/general-design/consolidation-of-extended-configurations/consolidation-of-extended-configurations.md
> +An exemplary use case for this feature is the usage of two identical **custom dropdown values** in two different **dropdown attributes**. You can now select one of the custom **values** as a **'maste
I fixed the wording in the description and added a small paragraph with a note that it is also possible to do the example with multiple slaves and one master

2021-03-19 15:42 UTC, saschabartsch commented on docs/admin/features/general-design/consolidation-of-extended-configurations/consolidation-of-extended-configurations.md
> +An exemplary use case for this feature is the usage of two identical **custom dropdown values** in two different **dropdown attributes**. You can now select one of the custom **values** as a **'maste
fixed

2021-03-19 20:58 UTC, thomashauser approved these changes

2021-03-19 20:58 UTC, merged