Added the instructions to configure Jira manually
ploetz-zeller/symbio-documentation pull request #203
Opened 2021-04-09 16:26 UTC by PZ-CFDuToit

Added instructions on how to configure Jira manually if the administrator selects not to let the external system configure Jira.

2021-04-12 22:17 UTC, thomashauser requested changes

2021-04-12 22:17 UTC, thomashauser commented on mkdocs.yml
> +        - Using Symbio to Atlassian: admin/services/atlassian-connector/manual_jira_configuration.md
Both entries have the same title.

2021-05-06 06:28 UTC, PZ-CFDuToit commented on mkdocs.yml
> +        - Using Symbio to Atlassian: admin/services/atlassian-connector/manual_jira_configuration.md
fixed

2021-05-06 06:37 UTC, PZ-CFDuToit commented
Requested changes has been made. Please review the PR again

2021-05-26 12:51 UTC, thomashauser approved these changes

2021-05-26 12:52 UTC, merged