Update the Visio Importer documentation
ploetz-zeller/symbio-documentation pull request #204
Opened 2021-04-30 07:37 UTC by FrankeLukas

Adds documentation for registration and usage.
Removes old entries and adds references.

2021-05-11 07:44 UTC, JochenLinnemann commented on docs/admin/services/visio-importer/login.md
> +You will receive an email containing the PIN after you registered successfully. Please contact support if you didn’t receive an email.
Shouldn't we add a support link / e-mail address here?

2021-05-11 07:49 UTC, JochenLinnemann requested changes
Can you add screenshots of the Administrative Area without "(Debug)" in the title?

2021-05-12 08:53 UTC, FrankeLukas commented on docs/admin/services/visio-importer/login.md
> +You will receive an email containing the PIN after you registered successfully. Please contact support if you didn’t receive an email.
Added a link to https://www.symbioworld.com/en/service/support/.

2021-05-12 08:54 UTC, FrankeLukas commented
Removed `(Debug)` from the images and added a reference to https://www.symbioworld.com/en/service/support/.

2021-05-12 10:10 UTC, JochenLinnemann approved these changes

2021-05-14 14:30 UTC, FrankeLukas commented
@JochenLinnemann I fixed the review comments from Ioana so this is good to go now.

2021-05-16 12:03 UTC, JochenLinnemann approved these changes

2021-05-16 12:04 UTC, merged