Documents as list feature
ploetz-zeller/symbio-documentation pull request #208
Opened 2021-06-22 13:55 UTC by MilicaBokonjic

2021-06-22 15:16 UTC, OscheibeSymbio approved these changes

2021-06-22 19:26 UTC, thomashauser requested changes

2021-06-22 19:26 UTC, thomashauser commented on mkdocs.yml
> +        - "Method: Method: Documents as a list (instead of architecture)": admin/features/repository-design/list-view-documents/list-view-documents.md
Ok, I have answer from Carina. Please move the new entry to the general design group. There is already an entry for "Systems as a list".

2021-06-23 08:20 UTC, MilicaBokonjic commented on mkdocs.yml
> +        - "Method: Method: Documents as a list (instead of architecture)": admin/features/repository-design/list-view-documents/list-view-documents.md
done

2021-06-23 08:48 UTC, thomashauser approved these changes

2021-06-23 08:48 UTC, merged